name: Deploy to Choreo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  BACKEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/health-planner-backend
  FRONTEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/health-planner-frontend

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          cd python-backend
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          cd python-backend
          python -m pytest tests/ || echo "No tests found"
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ui/package-lock.json
          
      - name: Install frontend dependencies
        run: |
          cd ui
          npm ci
          
      - name: Build frontend
        run: |
          cd ui
          npm run build

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.BACKEND_IMAGE }}:${{ github.sha }},${{ env.BACKEND_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./ui
          file: ./ui/Dockerfile
          push: true
          tags: ${{ env.FRONTEND_IMAGE }}:${{ github.sha }},${{ env.FRONTEND_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to Choreo
        run: |
          echo "Deployment to Choreo would happen here"
          echo "You can use Choreo CLI or API to deploy"
          echo "Backend Image: ${{ env.BACKEND_IMAGE }}:${{ github.sha }}"
          echo "Frontend Image: ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}"
          
      # Example: Deploy using Choreo CLI (if available)
      # - name: Install Choreo CLI
      #   run: |
      #     curl -L https://github.com/choreo/cli/releases/latest/download/choreo-cli-linux-amd64 -o choreo
      #     chmod +x choreo
      #     sudo mv choreo /usr/local/bin/
      #     
      # - name: Deploy Backend
      #   run: |
      #     choreo deploy backend \
      #       --image ${{ env.BACKEND_IMAGE }}:${{ github.sha }} \
      #       --env OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
      #     
      # - name: Deploy Frontend
      #   run: |
      #     choreo deploy frontend \
      #       --image ${{ env.FRONTEND_IMAGE }}:${{ github.sha }} \
      #       --env BACKEND_URL=${{ secrets.BACKEND_URL }} 